### ISSUE TITLE
Using two image types (.webp & .jpg) in responsive-image.html

### ISSUE THREAD

**Issue by slobodan-newprint** [wildlyinaccurate/jekyll-responsive-image#109]
I have a responsive-image.html that has .webp as a default image and .jpg as a fallback.

```
<picture>
  <!-- WebP Source with srcset -->
  <source type="image/webp" data-srcset="/path/to/image-200.webp 200w, /path/to/image-400.webp 400w, /path/to/image-800.webp 800w, /path/to/image-1000.webp 1000w, /path/to/image-2000.webp 2000w" />
  <!-- JPG Source with srcset -->
  <source type="image/jpg" data-srcset="/path/to/image-200.jpg 200w, /path/to/image-400.jpg 400w, /path/to/image-800.jpg 800w, /path/to/image-1000.jpg 1000w, /path/to/image-2000.jpg 2000w" />
  <img src="/path/to/image.jpg" alt="Am image" />
</picture>
```

is there a way to inject two file types in the responsive-image.html?

**Comment by danielpdykes** [comment]
Did you determine how to do this in the end @slobodan-newprint ?

**Comment by slobodan-newprint** [comment]
Hi @danielpdykes,

yes I did, I created image.html in **_includes** folder and called it like this **{% include image.html %}** and added **image** and **alt** variables that would be used in the image.html template.

`{% include image.html image="image-200.jpg" alt="Lorem Ipsum" %}`

You can then call the assigned values inside **image.html** like this

`{% assign webp_image = include.image | remove: ".jpg" | append: ".webp" %}`

I've used this code
`{% responsive_image_block %} 
        path: {{ include.image  | remove: ".jpg" | append: ".webp'" }}  
        alt: {{ include.alt }}
 {% endresponsive_image_block %}`

Hope this will help.

**Comment by danielpdykes** [comment]
Thank you - that was hugely helpful and set me in exactly the correct direction. Thanks for taking the time out of your day to reply.
