### ISSUE TITLE
Would it be possible to take source images from the post folder?

### ISSUE THREAD

**Issue by nhoizey** [wildlyinaccurate/jekyll-responsive-image#13]
As I wrote in [this comment on StackOverflow](http://stackoverflow.com/a/35270428/717195), most of —if not all— my images are useful in one single post, and keeping them alongside the Markdown file is really better for posts management.

For responsive images, I currently use the [Jekyll Picture Tag plugin](https://github.com/nhoizey/jekyll-picture-tag), but:
- It generates very verbose and sub-optimal `<picture>` elements, and I "only" need `srcset` and `sizes` attributes on most sites
- I had to fork it, because [my Pull Request to deal with such paths](https://github.com/robwierzbowski/jekyll-picture-tag/pull/60) was not accepted.

Would it be possible with this plugin, maybe with a new config option?

**Comment by wildlyinaccurate** [comment]
If I'm understanding your requirements correctly, this would be possible by allowing certain values like the post directory to be interpolated into `base_path`.

Feel free to experiment and submit a PR. Otherwise I can look into it when I get some free time over the next couple of weeks.

**Comment by borisschapira** [comment]
I think that @nhoizey it trying to include images that are inside the _posts folder :

```
| - _posts
  | - a_post_folder
    | - img
      | - 1.jpg
    | - a_post.md
  | - another_post_folder
    | - img
      | - 1.jpg
    | - another_post.md
```

So yes, you would need to dynamically detect the `base_path` and it would be different for every post's images. 

@nhoizey : how do you imagine the images to be stored into `_site` ?

**Comment by nhoizey** [comment]
Here is an example of my current way to store post images: [https://github.com/nhoizey/nicolas-hoizey.com/tree/master/_posts/2016/02/19-un-exemple-d-impact-des-raccourcisseurs-d-url](https://github.com/nhoizey/nicolas-hoizey.com/tree/master/_posts/2016/02/19-un-exemple-d-impact-des-raccourcisseurs-d-url)

@wildlyinaccurate `base_path` containing the post directory would be perfect.

@borisschapira as you can see with [this one](http://nicolas-hoizey.com/2016/02/19-un-exemple-d-impact-des-raccourcisseurs-d-url/impact-redirection-webperf-fibre-800by144-27af54.png), I currently have generated images also in the post folder, but I don't have any issue with generated images being in the same `assets/` subfolder if it's easier, I only need to put source images alongside their relative posts Markdown files.

**Comment by nhoizey** [comment]
I wonder if it would be possible to build another independant plugin that would solely allow us to set `images_source` and `images_destination` paths in `_config.yml`, with:
- default values both to `false` which would let current behavior untouched
- ability to use current post's paths (both source and destination including permalink)
- ability to use current post's metadata to "build" the source and destination paths

My current fork of the picture plugin let me set this:

```yaml
picture:
  source: "_posts"
  posts_folders: ":year/:month/:day-:slug/"
```

In fact, **a MVP approach for this plugin** would be to use the post's path as the source folder, and any arbitrary folder as the destination.
