### ISSUE TITLE
Error?

### ISSUE THREAD

**Issue by Ninetailz** [wildlyinaccurate/jekyll-responsive-image#14]
When trying to run the plugin, getting this

```
Configuration file: /home/ninetailz/forbidden/blog/_config.yml
/home/ninetailz/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:121:in `require': /home/ninetailz/forbidden/blog/_plugins/responsive_image.rb:5: syntax error, unexpected '<' (SyntaxError)
<!DOCTYPE html>
 ^
/home/ninetailz/forbidden/blog/_plugins/responsive_image.rb:6: syntax error, unexpected '<'
<html lang="en" class="">
 ^
/home/ninetailz/forbidden/blog/_plugins/responsive_image.rb:6: syntax error, unexpected keyword_class, expecting end-of-input
<html lang="en" class="">
                     ^
        from /home/ninetailz/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:121:in `require'
        from /home/ninetailz/.rvm/gems/ruby-2.2.1/gems/jekyll-3.0.1/lib/jekyll/plugin_manager.rb:75:in `block (2 levels) in require_plugin_files'
        from /home/ninetailz/.rvm/gems/ruby-2.2.1/gems/jekyll-3.0.1/lib/jekyll/plugin_manager.rb:74:in `each'
        from /home/ninetailz/.rvm/gems/ruby-2.2.1/gems/jekyll-3.0.1/lib/jekyll/plugin_manager.rb:74:in `block in require_plugin_files'
        from /home/ninetailz/.rvm/gems/ruby-2.2.1/gems/jekyll-3.0.1/lib/jekyll/plugin_manager.rb:73:in `each'
        from /home/ninetailz/.rvm/gems/ruby-2.2.1/gems/jekyll-3.0.1/lib/jekyll/plugin_manager.rb:73:in `require_plugin_files'
        from /home/ninetailz/.rvm/gems/ruby-2.2.1/gems/jekyll-3.0.1/lib/jekyll/plugin_manager.rb:18:in `conscientious_require'
        from /home/ninetailz/.rvm/gems/ruby-2.2.1/gems/jekyll-3.0.1/lib/jekyll/site.rb:97:in `setup'
        from /home/ninetailz/.rvm/gems/ruby-2.2.1/gems/jekyll-3.0.1/lib/jekyll/site.rb:49:in `initialize'
        from /home/ninetailz/.rvm/gems/ruby-2.2.1/gems/jekyll-3.0.1/lib/jekyll/commands/build.rb:30:in `new'
        from /home/ninetailz/.rvm/gems/ruby-2.2.1/gems/jekyll-3.0.1/lib/jekyll/commands/build.rb:30:in `process'
        from /home/ninetailz/.rvm/gems/ruby-2.2.1/gems/jekyll-3.0.1/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
        from /home/ninetailz/.rvm/gems/ruby-2.2.1/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `call'
        from /home/ninetailz/.rvm/gems/ruby-2.2.1/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `block in execute'
        from /home/ninetailz/.rvm/gems/ruby-2.2.1/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `each'
        from /home/ninetailz/.rvm/gems/ruby-2.2.1/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `execute'
        from /home/ninetailz/.rvm/gems/ruby-2.2.1/gems/mercenary-0.3.5/lib/mercenary/program.rb:42:in `go'
        from /home/ninetailz/.rvm/gems/ruby-2.2.1/gems/mercenary-0.3.5/lib/mercenary.rb:19:in `program'
        from /home/ninetailz/.rvm/gems/ruby-2.2.1/gems/jekyll-3.0.1/bin/jekyll:17:in `<top (required)>'
        from /home/ninetailz/.rvm/gems/ruby-2.2.1/bin/jekyll:23:in `load'
        from /home/ninetailz/.rvm/gems/ruby-2.2.1/bin/jekyll:23:in `<main>'
        from /home/ninetailz/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
        from /home/ninetailz/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'

```

please help.

Thanks,
Ninetailz

**Comment by wildlyinaccurate** [comment]
From that error, it looks like `responsive_image.rb`contains some HTML?

**Comment by Ninetailz** [comment]
Fixed this by using the gem, i think maybe i messed up caused i used wget to download that .rb file. I did have to reinstall rmagick to get this responsive gem working

Also i didn't know it should be listed as
gem:
  - jekyll/responsive-image

Please do update cause using the old way to list (jekyll-responsive_image) didn't work

**Comment by wildlyinaccurate** [comment]
That's strange, because the gem is called [jekyll-responsive_image](https://rubygems.org/gems/jekyll-responsive_image). I'm glad you got it working, anyway.

**Comment by Ninetailz** [comment]
yea its strange and you have it listed in your website the same way to not the usual name..

BTW is there a way to specify specific width and height using {% responsive_image path: assets/2.jpg width: something height: something %}

**Comment by hasselg** [comment]
I'm having the same problem with specifying the dependency. I used to just include the jekyll-response_image.rb file in my _includes to get around it.

If I specify
``
gems: [jekyll-response_image]
``
things don't work and I get the following error:
``
  Dependency Error: Yikes! It looks like you don't have jekyll-responsive_image or one of its dependencies installed. In order to use Jekyll as currently configured, you'll need to install this gem. The full error message from Ruby is: 'cannot load such file -- jekyll-responsive_image' If you run into trouble, you can find helpful resources at http://jekyllrb.com/help/!
``

However, if I specify
``
gems: [jekyll/responsive-image]
``
everything works.

**Comment by espurnes** [comment]
In my case the message appears if I set:
`gems: [jekyll/responsive-image]`

It is solved changing this line in _config.rb to:
`gems: [jekyll/responsive_image]`

I've installed the plugin specifying it in my Gemfile:
`source 'https://rubygems.org'
gem 'jekyll', '3.1.6'
gem 'jekyll-responsive_image'`

The gem name is equal in both places.

I hope it helps someone.

**Comment by espurnes** [comment]
In my case the message appears if I set:
`gems: [jekyll/responsive-image]`

It is solved changing this line in _config.rb to:
`gems: [jekyll/responsive_image]`

I've installed the plugin specifying it in my Gemfile:
`gem 'jekyll-responsive_image'`

The gem name is equal in both places.

I hope it helps someone.
