### ISSUE TITLE
Error installing the gem

### ISSUE THREAD

**Issue by mitchrenton** [wildlyinaccurate/jekyll-responsive-image#20]
I'm getting the following errors when installing the jekyll-responsive-image gem.

Do you have any idea why this is happening?

I'm currently running OS 10.10.5, Ruby 2.2.1, Jekyll 3.1.3, Node 5.5.0

---

Building native extensions.  This could take a while...
ERROR:  Error installing jekyll-responsive_image:
    ERROR: Failed to build gem native extension.

```
current directory: /Users/mitchrenton/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rmagick-2.15.4/ext/RMagick
```

/Users/mitchrenton/.rbenv/versions/2.3.1/bin/ruby -r ./siteconf20160511-55038-3z5fhr.rb extconf.rb
checking for clang... yes
checking for Magick-config... no
checking for pkg-config... yes
Package MagickCore was not found in the pkg-config search path.
Perhaps you should add the directory containing `MagickCore.pc'
to the PKG_CONFIG_PATH environment variable
No package 'MagickCore' found
checking for outdated ImageMagick version (<= 6.4.9)... **\* extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
    --with-opt-dir
    --without-opt-dir
    --with-opt-include
    --without-opt-include=${opt-dir}/include
    --with-opt-lib
    --without-opt-lib=${opt-dir}/lib
    --with-make-prog
    --without-make-prog
    --srcdir=.
    --curdir
    --ruby=/Users/mitchrenton/.rbenv/versions/2.3.1/bin/$(RUBY_BASE_NAME)

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /Users/mitchrenton/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/extensions/x86_64-darwin-14/2.3.0-static/rmagick-2.15.4/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /Users/mitchrenton/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rmagick-2.15.4 for inspection.

**Comment by wildlyinaccurate** [comment]
It looks like you're missing imagemagick. If you have homebrew, you can `brew install imagemagick`.

**Comment by mitchrenton** [comment]
Thanks for the response. That's got me a little closer for sure!

I now have this error.

`Dependency Error: Yikes! It looks like you don't have jekyll-responsive_image or one of its dependencies installed. In order to use Jekyll as currently configured, you'll need to install this gem. The full error message from Ruby is: 'cannot load such file -- jekyll-responsive_image' If you run into trouble, you can find helpful resources at http://jekyllrb.com/help/! `

I've installed the gem and it's dependencies so not sure what the issue is?

**Comment by h0r0man** [comment]
I have the same issue of @mitchrenton.

**Comment by wildlyinaccurate** [comment]
Apologies for the slow reply. Can you try using `jekyll/responsive_image` in your config instead of `jekyll/responsive-image`? I.e.

```yaml
# config.yaml
gems: [jekyll/responsive_image]
```

The instructions in the README previously advised doing this but some people reported in #14 that it only worked with `jekyll/responsive-image`. I'm not really sure which is the correct one since people seem to get different results.

**Comment by h0r0man** [comment]
@wildlyinaccurate same error: `Dependency Error: Yikes! It looks like you don't have jekyll-responsive_image or one of its dependencies installed. In order to use Jekyll as currently configured, you'll need to install this gem. The full error message from Ruby is: 'cannot load such file -- jekyll-responsive_image' If you run into trouble, you can find helpful resources at http://jekyllrb.com/help/!`

**Comment by eyesuk** [comment]
I was getting the same error but got around it by adding  
`[responsive_image]` vs `[jekyll/responsive_image]` in the .yaml file

However I am now getting this error
jekyll 3.0.3 | Error:  uninitialized constant Jekyll::ResponsiveImage::Utils

**Comment by AdityaAnand1** [comment]
Nothing above worked for me. Then I added it to the GEMFILE and it worked.

````
group :jekyll_plugins do
   gem 'jekyll-responsive-image'
end
````

But then I got a [different error](https://github.com/wildlyinaccurate/jekyll-responsive-image/issues/51) -.-

**Comment by natelandau** [comment]
I'm having the same problems.  Has anyone solved this yet?

**Comment by hasselg** [comment]
@natelandau  Are you by chance running Homebrew?

**Comment by natelandau** [comment]
@hasselg sorry for delay in response.  Yes, I am running homebrew and fixed the problem which had to do with rmagick not working with the newest version of imagemagick. I resolved the issue by following these steps to force Homebrew to use imagemagick6

```
gem uninstall rmagick
brew uninstall imagemagick
brew install imagemagick@6
brew link imagemagick@6 --force
bundle install
```

**Comment by xSAVIKx** [comment]
I'd like also to mention, how to install this plugin on Win10:
Download ImageMagic 6 (with needed OS architecture) from [here](https://www.imagemagick.org/download/binaries/).

Install to some location without spaces, e.g.: `c:\tools\imagemagic`.
During installation check  be sure to check following checkboxes:
* Install development headers and libraries for C and C++
* Install ImageMagicObject OLE Control for VBscript, Visual Basic, and WSH

Then install `rmagic` gem with following command, assuming you've installed image magic into `c\tools\imagemagic`:
```
gem install rmagick -- --with-opt-dir=c:\tools\imagemagic
```

Only after manual installation of `rmagic` you could install jekyll responsive image plugin:
```
gem install jekyll-responsive-image
```

I hope it'd be useful for someone :-)

**Comment by niij** [comment]
Install is broken on Linux as well. I tried installing ImageMagick through Linuxbrew, and following all of the above instructions.  I couldn't get past this:

```
Building native extensions.  This could take a while...
ERROR:  Error installing jekyll-responsive-image:
	ERROR: Failed to build gem native extension.

    current directory: /home/brandon/.rvm/gems/ruby-2.4.0/gems/rmagick-2.16.0/ext/RMagick
/home/brandon/.rvm/rubies/ruby-2.4.0/bin/ruby -r ./siteconf20170421-22285-ja5k0k.rb extconf.rb
checking for gcc... yes
checking for Magick-config... no
checking for pkg-config... yes
Package MagickCore was not found in the pkg-config search path.
Perhaps you should add the directory containing `MagickCore.pc'
to the PKG_CONFIG_PATH environment variable
No package 'MagickCore' found
checking for outdated ImageMagick version (<= 6.4.9)... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/home/brandon/.rvm/rubies/ruby-2.4.0/bin/$(RUBY_BASE_NAME)

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /home/brandon/.rvm/gems/ruby-2.4.0/extensions/x86_64-linux/2.4.0/rmagick-2.16.0/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /home/brandon/.rvm/gems/ruby-2.4.0/gems/rmagick-2.16.0 for inspection.
Results logged to /home/brandon/.rvm/gems/ruby-2.4.0/extensions/x86_64-linux/2.4.0/rmagick-2.16.0/gem_make.out
```

**Comment by niij** [comment]
After a lot of pain, I got it to install on Linux.  These instructions may be overkill, but it worked for me so :man_shrugging:

Install homebrew for linux (yuck, I know)
```
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install)"
export PATH="/home/YOURUSERNAMEGOESHERE/.linuxbrew/bin:$PATH"
```

Install imagemagick
```
brew install imagemagick@6
brew link --force imagemagick@6
```
Then install the responsive-image gem as normal.
```
gem install jekyll-responsive-image
```


**If that DOESN'T work, then do the following:**
```
sudo apt-get purge graphicsmagick graphicsmagick-dbg imagemagick-common imagemagick imagemagick-6.q16 libmagickcore-6-headers libmagickwand-dev
sudo apt-get autoremove
sudo apt-get install imagemagick libmagickwand-dev
sudo ln -s /usr/lib/x86_64-linux-gnu/ImageMagick-6.8.9/bin-Q16/Magick-config /usr/bin/Magick-config
gem install rmagick
gem install jekyll-responsive-image
```

**Comment by antgel** [comment]
There's absolutely no need to install linuxbrew on a modern Linux e.g. Ubuntu Xenial. Just `sudo apt install libmagickcore-6.q16-dev imagemagick` was enough for me.

**Comment by mariohernandez** [comment]
Not sure this is related but no matter what I do I continue to get this error `Liquid Exception: Invalid image path specified: assets/resized/1400/hero.png` when I build the site.
If I hard code the path the multiple image sources are generated successfully and the image srcset attribute prints the right images.  Can someone help me determine what the right `_config.yml` configuration is for `base_path` and `output_path_format` in addition to other tips that may help me successfully build the site when running the build command?

**Comment by mariohernandez** [comment]
... the error is originated from `{% responsive_image path: assets/resized/1400/hero.png %}`.

**Comment by wildlyinaccurate** [comment]
@mariohernandez you should use the original path with the `responsive_image` tag, not a resized image. Does it work with `{% responsive_image path: assets/hero.png %}`? If not, double-check that the file exists in the specified path.

**Comment by mariohernandez** [comment]
Hi @wildlyinaccurate, I get the same error when I use the original path.  I have confirmed the file does exist in the specified path.
I may be doing things differently and that could be contributing to the issue.  So basically I have created a component (`src/_includes/components/hero.html`).  This component is being included 
 in a styleguide we setup in the project located under (`src/_styleguide/components/hero.html`).  The error message I reported above is coming from the styleguide file, not the component itself.
Does that make sense?  
I wonder if the workflow we are following for the styleguide does not comply with Jekyll's workflow.  I'd appreciate your feedback.

**Comment by ao2137** [comment]
@niij Thank you so much.  I lost 4 hours to this and that fixed it, as you imply it is perhaps an ugly solution but it is a solution.

**Comment by mcrot** [comment]
Hi @mitchrenton,
today I got the same error when installing the plugin in Linux Mint.
The solution was that I needed some dev packages (with headers etc.) on OS level.
For me
```
sudo apt install libmagickcore-dev imagemagick libmagickwand-dev ruby-rmagick
```
was the solution. Before I added 
```
gem "jekyll-responsive_image"
```
to my `Gemfile` and used `bundle install`. Then the plugin was built without problems.

**Comment by pzmarzly** [comment]
After struggling to make it work on Arch (I had both ImageMagick 6 and 7 installed at the same time), I ended up making vagga container with the following `vagga.yaml`:

```yaml
containers:
  nogems:
    setup:
      - !Ubuntu xenial
      - !UbuntuUniverse
      - !Install
        - ruby-dev
        - build-essential
        - imagemagick
        - libmagickcore-dev
        - libmagickwand-dev
        - libgraphviz-dev
        - libgvc6-plugins-gtk
        - ruby-rmagick
      - !Sh gem install bundler
  gems:
    setup:
      - !Container nogems
      - !Sh bundle install
commands:
  shell: !Command
    container: gems
    run: "cd website && bash"
```

I use `vagga shell` to do stuff, and `vagga _build --force gems` to reinstall gems. I had to move Jekyll website into a subfolder, as Jekyll tries to watch all files in current directory (including vagga cache), even when they are excluded.

**Comment by aaronsarnat** [comment]
I know I'm a bit late to this party... I ran into installation issues with this plugin which is what led me to this thread. I just got the plugin working on my end and couldn't be happier.

Below is my local config and the recipe I used that worked. I'm writing this for anyone else who may stumble upon this thread looking for answers the way I did. Full disclosure: I'm only quasi-technical...

**My Setup:**
- `Mac OSX 10.14.5`
- `ImageMagick 6.9.10-43`
- `rmagick (3.1.0, 2.16.0)` - I had installed this manually awhile back, then looks like `jekyll-responsive-image` installed the older version. So far I haven't witnessed any conflicts. 
- `Jekyll 3.7.4`
- `jekyll-responsive-image (1.5.2)`
- `jekyll-responsive_image (1.0.1)` - Not sure how I got 2 versions of this installed?

Steps I took to get the plugin to work, assuming the above config. I'm not saying this is what you need to do, but this did work for me. I'd obviously defer to @wildlyinaccurate.

1. I Installed this plugin via:
    ```bash
    $ gem install jekyll-responsive-image
    ```

2. Then I added this line to my `Gemfile` (after finding [this](https://github.com/wildlyinaccurate/jekyll-responsive-image/issues/43#issuecomment-269885119)):
    ```ruby
    gem "jekyll-responsive-image", "~> 1.0"
    ```

3. Then I created an include file called `responsive-image.html` based on [this template](https://github.com/wildlyinaccurate/jekyll-responsive-image/blob/master/sample-templates/picture.html) and put it in the Jekyll `_includes` folder.

4. Then I added these lines to my `_config.yml`:
    ```yml
    plugins:
      - jekyll-responsive-image
    responsive_image:
      template: _includes/responsive-image.html
    ```

5. Then from my Jekyll project directory, I ran:
    ```bash
    $ bundle install
    ```

6. And finally, I started Jekyll...
    ```bash
    $ bundle exec jekyll serve
    ```
    And voila! It worked :)

Once I finally got it working, I was very happy to have the functionality. Thanks @wildlyinaccurate for creating this (and for engaging with your users). I desperately needed a clean way to get intrinsic image dimensions from assets in a folder so I could have Jekyll output those values to JSON... and then I found your plugin which lets me do exactly that.

Works BEAUTIFULLY! :D
