### ISSUE TITLE
Image sizes not being generated?

### ISSUE THREAD

**Issue by narthur** [wildlyinaccurate/jekyll-responsive-image#21]
Hey, must be missing something in the tutorial, but not sure why new images aren't being generated. An assets folder isn't being created, either. I installed the jekyll_responsive-image gem, put the extra config in my _config.yml file, and serving the site works fine, but no new images are being generated. What am I missing?

**Comment by narthur** [comment]
Just figured it out: your plugin is smart enough to only create resized versions of photos that are loaded in using your responsive_image include.

So, now I have a new question: Is there a way to tell your plugin to resize all images in a given folder, regardless of whether or not it detects they're being used? I'd like to use your plugin to do responsive CSS background images using media queries.

**Comment by wildlyinaccurate** [comment]
There's currently no functionality to resize images which aren't referenced by responsive_image or responsive_image_block. I think this is a reasonable addition to the plugin, though.

Maybe something like this?

```yaml
# By default, only images referenced by the responsive_image and responsive_image_block
# tags are resized. Here you can set a list of images or path globs to resize other
# images. This is useful for resizing images which will be referenced from stylesheets.
extra_images:
  - assets/foo/bar.png
  - assets/bgs/*.png
```

**Comment by narthur** [comment]
That would be perfect!

**Comment by bentiffany** [comment]
Perhaps an extra_images option could accept an array of glob style patterns? That would make it possible to resize everything in a directory, resize recursively, etc.

**Comment by wildlyinaccurate** [comment]
I've just released v0.17.0 of the gem - would you mind installing it and letting me know if the `extra_images` suits your needs?

**Comment by narthur** [comment]
As far as I can tell, works flawlessly! Thank you so much for your great work with this plugin.

**Comment by wildlyinaccurate** [comment]
Awesome! You're very welcome - I'm glad it's been useful!
