### ISSUE TITLE
responsive_image_block does not allow leading slash in path

### ISSUE THREAD

**Issue by caleb531** [wildlyinaccurate/jekyll-responsive-image#25]
Hi,

After searching far and wide for a practical responsive image plugin for Jekyll, I discovered this plugin, and it's really rocking so far... except for one small thing:

Every time I try to pass an image path beginning with a slash (*e.g.* `/assets/images/...`) to the `path` attribute for `responsive_image_block`, the build throws this error:

```
Liquid Exception: Invalid image path specified: /assets/images/...
```

I assume this happens for the `responsive_image` command also, though I personally haven't tested it because `responsive_image_block` is superior. :)

I can fix this using a `replace` filter (*e.g.* `path: {{ mypath | replace: '/assets', 'assets' }}`, but this isn't ideal. Could you possibly add some condition to handle this for me?

Thanks,
Caleb

**Comment by wildlyinaccurate** [comment]
Unfortunately you will have to keep stripping the leading slash from your paths. Treating all paths as relative would break the plugin for the people who use absolute paths.

**Comment by caleb531** [comment]
Fair enough, though FWIW, it always seemed to me that in a Jekyll context, `/` always referenced the root directory of the Jekyll site.

**Comment by sarahquigley** [comment]
Could some config be added specifying whether paths are relative or absolute? (With the default as absolute.)
