### ISSUE TITLE
Grabbing Specific Image Size

### ISSUE THREAD

**Issue by k-funk** [wildlyinaccurate/jekyll-responsive-image#26]
I'd like to this plugin, because it seems like it's the most robust among jekyll + imagemagic, but there seems to be no simple way of processing/grabbing a single image size.

/assets/image1.jpg
-> /assets/resized/400/image1.jpg
-> /assets/resized/800/image1.jpg

`<img src="/assets/resized/400/image1.jpg">`

It seems like including it in `extra_images` inside of `_config.yml` might work, but I don't want to have to define every image there, when I'm already going to be typing it in my html.

Any ideas on how to make it work simpler? I don't really need an array of sized images.

**Comment by wildlyinaccurate** [comment]
There's not currently a nice way to do this... The intention of the plugin is really that you use all of the image sizes to implement responsive images.

You could probably get a single size like this, though:

```mustache
{% for i in resized %}
    {% if i.width == 400 %}
        <img src="/{{ i.path }}">
    {% endif %}
{% endfor %}
```
