### ISSUE TITLE
extra_images globbing errors

### ISSUE THREAD

**Issue by k-funk** [wildlyinaccurate/jekyll-responsive-image#28]
Getting this error when using `*` globbing with the `extra_images` option: 

    jekyll 3.1.6 | Error:  no decode delegate for this image format `' @ error/constitute.c/ReadImage/504

Looks like it's being thrown by imagemagick.

**Comment by k-funk** [comment]
Was able to fix it by including file types in the glob:

      extra_images:
        - images/**/*.{jpeg,jpg}

I'm guessing it was trying to process `.DS_Store`'s or some other hidden file.

You can close this issue.

**Comment by wildlyinaccurate** [comment]
We could try to detect valid image files or something like that but I suspect that'll cause more problems than it'll solve! Thanks for the PR to update the readme, btw.
