### ISSUE TITLE
Use Height in sizing as well as Width

### ISSUE THREAD

**Issue by k-funk** [wildlyinaccurate/jekyll-responsive-image#29]
Feature request:
Allow height to be defined in the sizes, that will fit an image into the given dimensions heightXwidth as in the [first example on imagemagick's docs](http://www.imagemagick.org/Usage/resize/). To make it simpler, you could make it only respect height if width is already defined, and fail otherwise.

      sizes:
        - width: 180
          height: 120
          quality: 80

**Comment by wildlyinaccurate** [comment]
Apologies for the (very) late reply on this. It sounds like the intention here is to automatically crop images, which goes beyond the scope of this plugin. The focus of this plugin is to take the burden out of implementing responsive images. Given that responsive images deal with device width, I won't be adding any functionality around height in the foreseeable future.
