### ISSUE TITLE
Error: incompatible character encodings: UTF-8 and ASCII-8BIT

### ISSUE THREAD

**Issue by sarahquigley** [wildlyinaccurate/jekyll-responsive-image#30]
I encountered a small issue with this plugin: When I tried to pass a path containing a non-standard character (in my case, an ñ) to the responsive_image tag I got the following Liquid Exception:

```
Error: incompatible character encodings: UTF-8 and ASCII-8BIT
```

The plugin works perfectly as long as I stick to standard characters. 

Can this plugin be updated to avoid this issues (or is it a Liquid issue)? If it is possible to fix this from within the plugin, any plans to address this issue?

Thanks so much!

**Comment by wildlyinaccurate** [comment]
Thanks for the report! I won't be able to look into this for a few days. In the mean time could you please confirm whether it's definitely the plugin? I guess just having some non-ASCII characters in a post without the responsive_image tag.

**Comment by sarahquigley** [comment]
Thanks so much for your prompt response @wildlyinaccurate! I'm positive it's the plugin.

I encountered the error when I passed the following path to the responsive image tag: `/uploads/posts/recipes/2015-04-29-everybody-loves-jalapeño-pineapple-cornbread/DSC_0131.jpg` [Note: the ñ character]

As soon as I switched out the path I passed to the tag for `/uploads/posts/recipes/2015-04-29-everybody-loves-jalapeno-pineapple-cornbread/DSC_0131.jpg` [Note: the ñ replaced by an n] (or removed the reference to the responsive image tag altogether), my site returned to compiling without error. (The post itself still contained plenty of non ASCII characters.)

Thanks again. Great plugin by the way! I almost went down the route of building something similar myself, until I stumbled on your plugin and realised it did pretty much everything I needed. :) The properties on images are particularly useful.

**Comment by sarahquigley** [comment]
It may or may not be worth knowing that I'm running ruby 2.2.2 and liquid 3.0.6.

**Comment by wildlyinaccurate** [comment]
I'm really sorry that it took so long (life etc), but I finally found the time to look into this. I'm going to test the changes on a couple of my sites first. If all goes well I'll release a new version of the gem.

**Comment by sarahquigley** [comment]
@wildlyinaccurate No worries - I understand completely! Thanks so much for working on this. I'm excited to pull down the next version of your gem.

**Comment by wildlyinaccurate** [comment]
Okay, I'm pretty confident that nothing is broken so I've pushed these fixes out into the wild in the form of version 0.18.0. Feel free to reopen this issue if the new version doesn't fix it.

**Comment by sarahquigley** [comment]
Hey @wildlyinaccurate - I just upgraded to 0.18.0 and it's working great for me. Thanks so much for the fast turnaround on fixing this issue!
