### ISSUE TITLE
Feature request: recursive processing of directories

### ISSUE THREAD

**Issue by hasselg** [wildlyinaccurate/jekyll-responsive-image#4]
Hi @wildlyinaccurate,

I have a feature request. It'd be nice if all folders in the root could be recursively processed.

Starting with:
```
| - config.ml
| - assets
  | - postA
    | - 1A.jpg
  | - 1.jpg
```
Currently yields:
```
| - _site
  | - assets
    | - postA
      | - 1A.jpg    
    | - resized
      | - 1.jpg
    | - 1.jpg
```

I'd like it to yield:
```
| - _site
  | - assets
    | - postA
      | - 1A.jpg    
    | - resized
      | - postA
        | - 1A.jpg
      | - 1.jpg
    | - 1.jpg
```

Thanks,

Greg

**Comment by wildlyinaccurate** [comment]
Hey Greg, thanks for the feature request -- that's a totally valid case that I hadn't even considered.

I'll get onto it ASAP.

**Comment by wildlyinaccurate** [comment]
This is possible since v0.14.0 with the new `dirname` value. For example you could set `output_path_format` to something like `assets/resized/%{dirname}/%{filename}-%{width}x%{height}.%{extension}`.
