### ISSUE TITLE
uninitialized constant Jekyll::ResponsiveImage::Utils

### ISSUE THREAD

**Issue by eyesuk** [wildlyinaccurate/jekyll-responsive-image#43]
jekyll 3.0.3 | Error:  uninitialized constant Jekyll::ResponsiveImage::Utils
Did you mean?  Jekyll::Utils

**Comment by eyesuk** [comment]
Sorry for the update of this issue we are having. I am trying everything I can and end up in the error above

**Comment by wildlyinaccurate** [comment]
Please could you state which version of jekyll-responsive-image you are using?

I've very recently renamed the gem from `jekyll/responsive_image` to `jekyll-responsive-image` so you can try installing that instead.

**Comment by eyesuk** [comment]
Hello sir,
I am using jekyll-responsive-image (1.1.0)

**Comment by wildlyinaccurate** [comment]
Does your _config.yml contain the correct gem name? Something like:

```yaml
gems:
  - jekyll-responsive-image
```

**Comment by eyesuk** [comment]
yes it has this entry

`gems: ['jekyll-paginate','jekyll-srcset','jekyll-responsive-image']`

**Comment by wildlyinaccurate** [comment]
Please can you run `jekyll build --verbose --trace` and paste the output here?

**Comment by eyesuk** [comment]
Sure thing...
Thanks for helping

`MBPr:csus eyesuk$ jekyll build --verbose --trace
  Logging at level: debug
Configuration file: /Users/eyesuk/Desktop/CSUS/_config.yml
/Users/eyesuk/Desktop/CSUS/_plugins/block.rb:4:in `<class:Block>': uninitialized constant Jekyll::ResponsiveImage::Utils (NameError)
Did you mean?  Jekyll::Utils
	from /Users/eyesuk/Desktop/CSUS/_plugins/block.rb:3:in `<module:ResponsiveImage>'
	from /Users/eyesuk/Desktop/CSUS/_plugins/block.rb:2:in `<module:Jekyll>'
	from /Users/eyesuk/Desktop/CSUS/_plugins/block.rb:1:in `<top (required)>'
	from /Users/eyesuk/.rvm/gems/ruby-2.3.1/gems/jekyll-3.0.3/lib/jekyll/plugin_manager.rb:75:in `require'
	from /Users/eyesuk/.rvm/gems/ruby-2.3.1/gems/jekyll-3.0.3/lib/jekyll/plugin_manager.rb:75:in `block (2 levels) in require_plugin_files'
	from /Users/eyesuk/.rvm/gems/ruby-2.3.1/gems/jekyll-3.0.3/lib/jekyll/plugin_manager.rb:74:in `each'
	from /Users/eyesuk/.rvm/gems/ruby-2.3.1/gems/jekyll-3.0.3/lib/jekyll/plugin_manager.rb:74:in `block in require_plugin_files'
	from /Users/eyesuk/.rvm/gems/ruby-2.3.1/gems/jekyll-3.0.3/lib/jekyll/plugin_manager.rb:73:in `each'
	from /Users/eyesuk/.rvm/gems/ruby-2.3.1/gems/jekyll-3.0.3/lib/jekyll/plugin_manager.rb:73:in `require_plugin_files'
	from /Users/eyesuk/.rvm/gems/ruby-2.3.1/gems/jekyll-3.0.3/lib/jekyll/plugin_manager.rb:18:in `conscientious_require'
	from /Users/eyesuk/.rvm/gems/ruby-2.3.1/gems/jekyll-3.0.3/lib/jekyll/site.rb:97:in `setup'
	from /Users/eyesuk/.rvm/gems/ruby-2.3.1/gems/jekyll-3.0.3/lib/jekyll/site.rb:49:in `initialize'
	from /Users/eyesuk/.rvm/gems/ruby-2.3.1/gems/jekyll-3.0.3/lib/jekyll/commands/build.rb:30:in `new'
	from /Users/eyesuk/.rvm/gems/ruby-2.3.1/gems/jekyll-3.0.3/lib/jekyll/commands/build.rb:30:in `process'
	from /Users/eyesuk/.rvm/gems/ruby-2.3.1/gems/jekyll-3.0.3/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
	from /Users/eyesuk/.rvm/gems/ruby-2.3.1/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `block in execute'
	from /Users/eyesuk/.rvm/gems/ruby-2.3.1/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `each'
	from /Users/eyesuk/.rvm/gems/ruby-2.3.1/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `execute'
	from /Users/eyesuk/.rvm/gems/ruby-2.3.1/gems/mercenary-0.3.5/lib/mercenary/program.rb:42:in `go'
	from /Users/eyesuk/.rvm/gems/ruby-2.3.1/gems/mercenary-0.3.5/lib/mercenary.rb:19:in `program'
	from /Users/eyesuk/.rvm/gems/ruby-2.3.1/gems/jekyll-3.0.3/bin/jekyll:17:in `<top (required)>'
	from /Users/eyesuk/.rvm/gems/ruby-2.3.1/bin/jekyll:22:in `load'
	from /Users/eyesuk/.rvm/gems/ruby-2.3.1/bin/jekyll:22:in `<main>'
	from /Users/eyesuk/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
	from /Users/eyesuk/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'`

**Comment by eyesuk** [comment]
When I remove the .rb files from the _plugin folder associated with responsive_iamge and run Jekyll verbose I get the following:

MBPr:csus eyesuk$ jekyll build --verbose --trace
  Logging at level: debug
Configuration file: /Users/eyesuk/Desktop/CSUS/_config.yml
     PluginManager: Requiring jekyll-paginate
     PluginManager: Requiring jekyll-responsive-image
/Users/eyesuk/.rvm/gems/ruby-2.3.1/gems/jekyll-3.0.3/lib/jekyll/plugin_manager.rb:30:in `require': cannot load such file -- jekyll-responsive-image (LoadError)
	from /Users/eyesuk/.rvm/gems/ruby-2.3.1/gems/jekyll-3.0.3/lib/jekyll/plugin_manager.rb:30:in `block in require_gems'
	from /Users/eyesuk/.rvm/gems/ruby-2.3.1/gems/jekyll-3.0.3/lib/jekyll/plugin_manager.rb:27:in `each'
	from /Users/eyesuk/.rvm/gems/ruby-2.3.1/gems/jekyll-3.0.3/lib/jekyll/plugin_manager.rb:27:in `require_gems'
	from /Users/eyesuk/.rvm/gems/ruby-2.3.1/gems/jekyll-3.0.3/lib/jekyll/plugin_manager.rb:19:in `conscientious_require'
	from /Users/eyesuk/.rvm/gems/ruby-2.3.1/gems/jekyll-3.0.3/lib/jekyll/site.rb:97:in `setup'
	from /Users/eyesuk/.rvm/gems/ruby-2.3.1/gems/jekyll-3.0.3/lib/jekyll/site.rb:49:in `initialize'
	from /Users/eyesuk/.rvm/gems/ruby-2.3.1/gems/jekyll-3.0.3/lib/jekyll/commands/build.rb:30:in `new'
	from /Users/eyesuk/.rvm/gems/ruby-2.3.1/gems/jekyll-3.0.3/lib/jekyll/commands/build.rb:30:in `process'
	from /Users/eyesuk/.rvm/gems/ruby-2.3.1/gems/jekyll-3.0.3/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
	from /Users/eyesuk/.rvm/gems/ruby-2.3.1/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `block in execute'
	from /Users/eyesuk/.rvm/gems/ruby-2.3.1/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `each'
	from /Users/eyesuk/.rvm/gems/ruby-2.3.1/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `execute'
	from /Users/eyesuk/.rvm/gems/ruby-2.3.1/gems/mercenary-0.3.5/lib/mercenary/program.rb:42:in `go'
	from /Users/eyesuk/.rvm/gems/ruby-2.3.1/gems/mercenary-0.3.5/lib/mercenary.rb:19:in `program'
	from /Users/eyesuk/.rvm/gems/ruby-2.3.1/gems/jekyll-3.0.3/bin/jekyll:17:in `<top (required)>'
	from /Users/eyesuk/.rvm/gems/ruby-2.3.1/bin/jekyll:22:in `load'
	from /Users/eyesuk/.rvm/gems/ruby-2.3.1/bin/jekyll:22:in `<main>'
	from /Users/eyesuk/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
	from /Users/eyesuk/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'

**Comment by wildlyinaccurate** [comment]
This looks like the gem is not installed. Does `gem install jekyll-responsive-image` fix it?

**Comment by eyesuk** [comment]
I tried that I few times and I still get the error:


MBPr:csus eyesuk$ gem install jekyll-responsive-image
Successfully installed jekyll-responsive-image-1.1.0
1 gem installed
MBPr:csus eyesuk$ jekyll build --verbose --trace
  Logging at level: debug
Configuration file: /Users/eyesuk/Desktop/CSUS/_config.yml
     PluginManager: Requiring jekyll-paginate
     PluginManager: Requiring jekyll-responsive-image
/Users/eyesuk/.rvm/gems/ruby-2.3.1/gems/jekyll-3.0.3/lib/jekyll/plugin_manager.rb:30:in `require': cannot load such file -- jekyll-responsive-image (LoadError)
	from /Users/eyesuk/.rvm/gems/ruby-2.3.1/gems/jekyll-3.0.3/lib/jekyll/plugin_manager.rb:30:in `block in require_gems'
	from /Users/eyesuk/.rvm/gems/ruby-2.3.1/gems/jekyll-3.0.3/lib/jekyll/plugin_manager.rb:27:in `each'
	from /Users/eyesuk/.rvm/gems/ruby-2.3.1/gems/jekyll-3.0.3/lib/jekyll/plugin_manager.rb:27:in `require_gems'
	from /Users/eyesuk/.rvm/gems/ruby-2.3.1/gems/jekyll-3.0.3/lib/jekyll/plugin_manager.rb:19:in `conscientious_require'
	from /Users/eyesuk/.rvm/gems/ruby-2.3.1/gems/jekyll-3.0.3/lib/jekyll/site.rb:97:in `setup'
	from /Users/eyesuk/.rvm/gems/ruby-2.3.1/gems/jekyll-3.0.3/lib/jekyll/site.rb:49:in `initialize'
	from /Users/eyesuk/.rvm/gems/ruby-2.3.1/gems/jekyll-3.0.3/lib/jekyll/commands/build.rb:30:in `new'
	from /Users/eyesuk/.rvm/gems/ruby-2.3.1/gems/jekyll-3.0.3/lib/jekyll/commands/build.rb:30:in `process'
	from /Users/eyesuk/.rvm/gems/ruby-2.3.1/gems/jekyll-3.0.3/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
	from /Users/eyesuk/.rvm/gems/ruby-2.3.1/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `block in execute'
	from /Users/eyesuk/.rvm/gems/ruby-2.3.1/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `each'
	from /Users/eyesuk/.rvm/gems/ruby-2.3.1/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `execute'
	from /Users/eyesuk/.rvm/gems/ruby-2.3.1/gems/mercenary-0.3.5/lib/mercenary/program.rb:42:in `go'
	from /Users/eyesuk/.rvm/gems/ruby-2.3.1/gems/mercenary-0.3.5/lib/mercenary.rb:19:in `program'
	from /Users/eyesuk/.rvm/gems/ruby-2.3.1/gems/jekyll-3.0.3/bin/jekyll:17:in `<top (required)>'
	from /Users/eyesuk/.rvm/gems/ruby-2.3.1/bin/jekyll:22:in `load'
	from /Users/eyesuk/.rvm/gems/ruby-2.3.1/bin/jekyll:22:in `<main>'
	from /Users/eyesuk/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
	from /Users/eyesuk/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'

**Comment by eyesuk** [comment]
Hello sir,
thanks for helping me I really appreciate it. I added the entry in the `Gemfile` and I got this error


MBPr-2:csus eyesuk$ jekyll build --verbose --trace
/Users/eyesuk/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.7/lib/bundler/resolver.rb:366:in `block in verify_gemfile_dependencies_are_found!': Could not find gem 'jekyll-responsive-image (~> 0.1)' in any of the gem sources listed in your Gemfile or available on this machine. (Bundler::GemNotFound)
	from /Users/eyesuk/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.7/lib/bundler/resolver.rb:341:in `each'
	from /Users/eyesuk/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.7/lib/bundler/resolver.rb:341:in `verify_gemfile_dependencies_are_found!'
	from /Users/eyesuk/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.7/lib/bundler/resolver.rb:199:in `start'
	from /Users/eyesuk/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.7/lib/bundler/resolver.rb:181:in `resolve'
	from /Users/eyesuk/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.7/lib/bundler/definition.rb:250:in `resolve'
	from /Users/eyesuk/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.7/lib/bundler/definition.rb:174:in `specs'
	from /Users/eyesuk/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.7/lib/bundler/definition.rb:233:in `specs_for'
	from /Users/eyesuk/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.7/lib/bundler/definition.rb:222:in `requested_specs'
	from /Users/eyesuk/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.7/lib/bundler/runtime.rb:118:in `block in definition_method'
	from /Users/eyesuk/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.7/lib/bundler/runtime.rb:19:in `setup'
	from /Users/eyesuk/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.7/lib/bundler.rb:99:in `setup'
	from /Users/eyesuk/.rvm/gems/ruby-2.3.1/gems/jekyll-3.3.1/lib/jekyll/plugin_manager.rb:36:in `require_from_bundler'
	from /Users/eyesuk/.rvm/gems/ruby-2.3.1/gems/jekyll-3.3.1/exe/jekyll:9:in `<top (required)>'
	from /Users/eyesuk/.rvm/gems/ruby-2.3.1/bin/jekyll:22:in `load'
	from /Users/eyesuk/.rvm/gems/ruby-2.3.1/bin/jekyll:22:in `<main>'
	from /Users/eyesuk/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
	from /Users/eyesuk/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'

**Comment by wildlyinaccurate** [comment]
Great, I'm glad that worked! Thanks for providing me with all the information. I'll update the README to include these instructions.

Thank you very much for the offer, but I have plenty of 🍺 right now — send me some positive vibes instead 😁

**Comment by eyesuk** [comment]
I got you! Positives vibes all the way... thanks for your help, I really appreciate it...

**Comment by aaronsarnat** [comment]
Sorry for the the random and late response, but the thread on this issue is what helped me solve an installation problem I was having. Thanks so much you guys! Also love the good vibes. :)

Also, love the plugin. :)
