### ISSUE TITLE
Order of images sizes in _config.yml

### ISSUE THREAD

**Issue by viv-b** [wildlyinaccurate/jekyll-responsive-image#45]
Hi. I'm a newbie to Jekyll but managed to get the plugin to work and it works well :) I used your example config from the README file. I found I needed to reverse the order of the 'sizes' when using the <picture> tag template so that they were largest to smallest. Otherwise the browser kept using the smallest image even on the large screen. So:

sizes:
    - width: 480  
      quality: 80
    - width: 800
    - width: 1400
      quality: 90

was changed to:

sizes:
    - width: 1400
      quality: 90
    - width: 800
    - width: 480  
      quality: 80

... and it seems to work as expected.

**Comment by wildlyinaccurate** [comment]
Yep, that sounds right — the `sizes` config is a plain old array and the order should be preserved when using it in templates.

Just out of curiosity, what are you using for responsive images that required the images to be listed largest -> smallest?

**Comment by viv-b** [comment]
Thanks for the quick reply. I'm just playing with it at the moment for future reference.  I just thought I'd mention it in that if I applied your code exactly as is using the <picture> tag template, it wasn't working for me in Chrome. Not until the output of the picture tags was in the largest to smallest order.

Just wondering also if there is a way to supply a variable for the image path tag rather than it being hard-coded each time? Cheers.

**Comment by wildlyinaccurate** [comment]
Oh that's interesting, I haven't used the picture tag much so I'll play around with it next week and update the documentation as necessary.

For the variable in path thing, you can use the `responsive_image_block` tag like this: https://github.com/wildlyinaccurate/jekyll-responsive-image/blob/master/features/responsive-image-block.feature#L10-L15

**Comment by viv-b** [comment]
Excellent, the responsive_image_block tag is just what I needed along with being able to switch to custom templates. Works well to wire-up a lightbox with thumbnail images linking to larger versions. Thanks :)
