### ISSUE TITLE
{{ page.id }} fails to be passed into the plugin when used within a custom excerpt section

### ISSUE THREAD

**Issue by mezpahlan** [wildlyinaccurate/jekyll-responsive-image#48]
I'm using the block format instead of the tag because I want to do something like this:

```
{% responsive_image_block %}
    path: {{ site.responsive_image.base_path | append: page.id | append: "/image-name.jpg" }}
    alt: "Image caption"
{% endresponsive_image_block %}
```
However I get the following error for a post named `2009-03-15-post-title.md`:

```
Liquid Exception: Invalid image path specified: assets/images/fullsize/blog/2009/03/15/post-title#excerpt/image-name.jpg 
```

Notice that `#excerpt` appears in the error output. I have no idea where that comes from or why it seems to be added onto the end of `page.id`.

I've tried to `{% assign path = {{ site.responsive_image.base_path | append: page.id | append: "/image-name.jpg" }} %}` separately and then use the `{{ path }}` in the responsive_image_block, however that doesn't work either.

I've also confirmed that `{{ site.responsive_image.base_path | append: page.id | append: "/image-name.jpg" }}` outside of the responsive_image_block outputs the correct string without `#excerpt`.

The only thing that worked was explicitly writing out the path instead of using variables like so:

```
{% responsive_image_block %}
    path: "assets/images/fullsize/blog/2009/03/15/post-title/image-name.jpg"
    alt: "Image caption"
{% endresponsive_image_block %}
```

But obviously I'd like to make use of the variables I already have access to like I do elsewhere in my jekyll blog. `site.responsive_image.base_path` is defined in the `_config.yml`, and `page.id` is defined as part of Jekyll so the only thing I need to worry about is what the image is called.

Many thanks.

**Comment by mezpahlan** [comment]
Hmmm....... this is very strange. I tried this again just now and it _looks_ like it is working as desired. I'll close this for now and reopen if I spot it again. Sorry for the confusion.

**Comment by mezpahlan** [comment]
Aaaand now it stopped working. Although I think I got to the bottom of it.

I use a custom excerpt marker. When I use your plugin from within the excerpt it fails with the same characteristics as I described in the original comment. i.e. it translates `{{ page.id }}` into `page/id/post-title#excerpt`. When I remove the excerpt marker from within my post I don't see that error.

I'm trying to port my site over from using the [Jekyll Picture Tag](https://github.com/robwierzbowski/jekyll-picture-tag/) plugin to using yours. I'm almost there but there is something in the way that jekyll-picture-tag worked that is holding me back fully porting over to use yours.

Having a look at [this piece of code](https://github.com/robwierzbowski/jekyll-picture-tag/blob/master/lib/jekyll-picture-tag.rb) from that project, it looks like they forcefully parse the parameters sent into the tag and strip out any unwanted characters / strings.

For the time being I can do something like this to workaround the issue.

```
path: {{ site.responsive_image.base_path | append: page.id | remove_first: "#excerpt" | append: "/image-name.png" }}
```

My config looks like this for the excerpt settings.

```
excerpt_separator: <!-- more -->
```

If you don't mind I'm going to reopen this so that you can have a look and let me know. I'll also try and edit the title to be a bit more specific as to the fact it is a bug only within the excerpt boundary.

**Comment by wildlyinaccurate** [comment]
Hey, thanks for the detailed report! I've just created a (failing) test case in #50. I'm pretty busy this week but I'll let it mull in my head for a bit and hopefully come up with a fix this weekend.

**Comment by wildlyinaccurate** [comment]
I was looking at this again today and I'm not sure it's something that this plugin can fix. When you write

```yaml
{% responsive_image_block %}
    path: {{ page.id }}
{% endresponsive_image_block %}
```

The `{{ page.id }}` part is evaluated before the plugin receives the value. By the time the plugin is initialised, all it receives is:

```yaml
path: /2017/03/13/my-post
```

So unfortunately to get around this, you'll need to continue stripping `#excerpt` from the paths.
