### ISSUE TITLE
Optionally remove resized images from source directory

### ISSUE THREAD

**Issue by mezpahlan** [wildlyinaccurate/jekyll-responsive-image#49]
Would it be possible to optionally remove (or ideally not create in the first place) the resized images from the source directory and only keep them in the target `_site` directory?

My Jekyll set up is a single repo with `source` branch and a git submodule for the `master` branch. The `source` branch contains all the posts in markdown format and the `master` branch contains the built site.

I do check the resized images into source control but don't want to check them in twice. Is this something that can be accommodated?

**Comment by wildlyinaccurate** [comment]
That sounds pretty similar to some of my setups. My resize images all go into an assets/resized directory which is easy to add to `.gitignore`, but I realise not everyone uses a separate directory for the resized images.

I'll look into adding an option to only create resized images in the destination directory.

**Comment by mezpahlan** [comment]
Oh yes of course, how silly of me. I could simply gitignore the resized
images in the source directory. If there was also an option to only create
them in the target directory that would be great too! Cheers.
