### ISSUE TITLE
jekyll 3.4.4 | Error:  no implicit conversion of nil into Hash

### ISSUE THREAD

**Issue by stevenmunro** [wildlyinaccurate/jekyll-responsive-image#60]
`jekyll serve --trace`

I don't know what it means, but here is the output.

`/usr/local/lib/ruby/gems/2.4.0/gems/jekyll-responsive-image-1.2.0/lib/jekyll-responsive-image/config.rb:18:in `merge': no implicit conversion of nil into Hash (TypeError)
	from /usr/local/lib/ruby/gems/2.4.0/gems/jekyll-responsive-image-1.2.0/lib/jekyll-responsive-image/config.rb:18:in `to_h'
	from /usr/local/lib/ruby/gems/2.4.0/gems/jekyll-responsive-image-1.2.0/lib/jekyll-responsive-image/extra_image_generator.rb:7:in `generate'
	from /usr/local/lib/ruby/gems/2.4.0/gems/jekyll-3.4.4/lib/jekyll/site.rb:174:in `block in generate'
	from /usr/local/lib/ruby/gems/2.4.0/gems/jekyll-3.4.4/lib/jekyll/site.rb:172:in `each'
	from /usr/local/lib/ruby/gems/2.4.0/gems/jekyll-3.4.4/lib/jekyll/site.rb:172:in `generate'
	from /usr/local/lib/ruby/gems/2.4.0/gems/jekyll-3.4.4/lib/jekyll/site.rb:68:in `process'
	from /usr/local/lib/ruby/gems/2.4.0/gems/jekyll-3.4.4/lib/jekyll/command.rb:26:in `process_site'
	from /usr/local/lib/ruby/gems/2.4.0/gems/jekyll-3.4.4/lib/jekyll/commands/build.rb:63:in `build'
	from /usr/local/lib/ruby/gems/2.4.0/gems/jekyll-3.4.4/lib/jekyll/commands/build.rb:34:in `process'
	from /usr/local/lib/ruby/gems/2.4.0/gems/jekyll-livereload-0.2.2/lib/jekyll-livereload/build.rb:30:in `process'
	from /usr/local/lib/ruby/gems/2.4.0/gems/jekyll-3.4.4/lib/jekyll/commands/serve.rb:37:in `block (2 levels) in init_with_program'
	from /usr/local/lib/ruby/gems/2.4.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
	from /usr/local/lib/ruby/gems/2.4.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
	from /usr/local/lib/ruby/gems/2.4.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
	from /usr/local/lib/ruby/gems/2.4.0/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
	from /usr/local/lib/ruby/gems/2.4.0/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
	from /usr/local/lib/ruby/gems/2.4.0/gems/jekyll-3.4.4/exe/jekyll:13:in `<top (required)>'
	from /usr/local/bin/jekyll:22:in `load'
	from /usr/local/bin/jekyll:22:in `<main>'`

**Comment by wildlyinaccurate** [comment]
Please can you paste your _config.yml here? It looks like you are missing the `responsive_image` section.

**Comment by mariohernandez** [comment]
I am experiencing the same issue.  Here's what my _config.yml looks like:
`title: Your awesome title
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/my-local" # the subpath of your site, e.g. /blog
url: "/" # the base hostname & protocol for your site, e.g. http://example.com

# Point Jekyll at the source file location.
source: ./src

# Build destination for all compiled site files.
destination: ./public

# Styleguide settings
collections:
  styleguide:
    output: true
  blogs:
    output: true
    permalink: /:path/:title.:output_ext

defaults:
  -
    scope:
      path: ""
      type: "styleguide"
    values:
      layout: "styleguide"

# Build settings
markdown: kramdown

gems:
  - jekyll-feed
  - jekyll-responsive-image

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - gulp-tasks
  - gulpfile.js
  - npm-shrinkwrap.json
  - README.md
  - package.json

keep_files:
  - css
  - js
  - assets
`

**Comment by wildlyinaccurate** [comment]
@mariohernandez you are missing the `responsive_image` config section. You can find an example config [in the README](https://github.com/wildlyinaccurate/jekyll-responsive-image#configuration).

**Comment by aviogit** [comment]
It happened to me too, maybe you should just replace:

«Configuration
An example configuration is below.»

with

«Configuration
An example configuration is below. Just copy/paste at the end of your _config.yml.»

Anyway, wonderful plugin, works marvelously thanks!
