### ISSUE TITLE
[Feature Request] Caching Option in Jekyll _config File

### ISSUE THREAD

**Issue by queued37** [wildlyinaccurate/jekyll-responsive-image#66]
Because of a long build time, I'm currently applying "cache: true" attributes to all responsive_image tags.
(Though this option is not documented in the README file, I anyhow looked up the code and found it. It needs to be documented.)
But I think there is no way to trigger the caching option in a batch without manually adding the attributes for now. It would be nice to have caching option in Jekyll's config file so that it can be triggered in development and turned off in production.

**Comment by wildlyinaccurate** [comment]
Ah, thanks for raising this! The `cache` attribute is undocumented because I initally wrote it as an experiment to speed up my own build times but never got around to fully testing it. I will add it as an option in the config now, though.

**Comment by wildlyinaccurate** [comment]
This should be available in version 1.4.0 of the gem.
