### ISSUE TITLE
tag responsive_image_block is not a recognized Liquid tag in production

### ISSUE THREAD

**Issue by jai-singhal** [wildlyinaccurate/jekyll-responsive-image#69]
Hello. I am using the "responsive_image_block" plugin on jekyll blog, it is working fine when I try running on locally, but it fails when I push on Github. It throws an error 
` Your site is having problems building: The tag responsive_image_block on line 10 in _posts/2017-01-15-welcome-to-jekyll.markdown is not a recognized Liquid tag.`

**Comment by wildlyinaccurate** [comment]
GitHub [only supports a limited set of plugins](https://help.github.com/articles/adding-jekyll-plugins-to-a-github-pages-site/), and unfortunately this is not one of them. If you want to publish your site to GitHub Pages, you'll have to generate it locally and push the `_site/` directory to GitHub instead.

**Comment by ngocsangyem** [comment]
I have same issue, then I switch Github page to [vercel](https://vercel.com/) and it works perfectly.
