### ISSUE TITLE
responsive_image_block error

### ISSUE THREAD

**Issue by derpayatz** [wildlyinaccurate/jekyll-responsive-image#70]
Hi! 

I am getting the following error when using responsive_image_block:
`` ~/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/psych.rb:377:in `parse': (<unknown>): mapping values are not allowed in this context``

This is my code:

    {%- capture path -%} assets/images/_sources/{{ page.featured-image.path | default: site.featured-
    image.path }} {%- endcapture -%}
    {%- capture alt -%} {{ page.image.alt | default: site.featured-image.path }} {%- endcapture -%}
    {% responsive_image_block -%}
      path: {{ path }}
      alt: {{ alt }}
    {%- endresponsive_image_block -%}

The `responsive_image` tag works, but I need to use Liquid variables.
Thank you.

**Comment by derpayatz** [comment]
It turns out that the tag works with no leading whitespace at all inside the block. Perhaps this can be made clearer in the documentation?

**Comment by wildlyinaccurate** [comment]
It should work fine with whitespace, so long as the indentation is consistent (this is [mentioned in the docs](https://github.com/wildlyinaccurate/jekyll-responsive-image#liquid-variables-as-attributes)). There are even [tests](https://github.com/wildlyinaccurate/jekyll-responsive-image/blob/master/features/responsive-image-block.feature#L6-L11) to make sure this works, although none of the tests use whitespace control like you are in that code (`{%- ... -%}`).

Was the indentation within that block using tabs or spaces?

**Comment by derpayatz** [comment]
The indentation was using spaces.

**Comment by kylekirkby** [comment]
I fixed the same error by adding quotes around the title: {{post.title}} -> title: "{{post.title}}"

**Comment by grauschnabel** [comment]
Hi there, I have the same issue, but how to I fix that?

**Comment by grauschnabel** [comment]
my problem was different. surrounding {{ path }}  and {{ alt }} with '' worked fine.  Maybe a sentence will be handled like a list of strings instead of a string?

**Comment by wildlyinaccurate** [comment]
@grauschnabel the `responsive_image_block` contents are parsed as YAML, which supports unquoted strings as well as quoted strings:

```yaml
unquoted: I am an unquoted string
single_quotes: 'This works too'
double_quotes: "And this"
```

If you don't know the contents of the string beforehand, it's probably better to use quotes just to be safe. It might even be best to escape the contents, e.g.

```yaml
title: "{{ title | escape }}"
```
