### ISSUE TITLE
Usability: When site config is not present, jekyll dies with unspecific error message

### ISSUE THREAD

**Issue by SebastianApel** [wildlyinaccurate/jekyll-responsive-image#72]
Situation:
* After installing jekyll-responsive-image, jekyll died with the following error message:
jekyll 3.7.3 | Error:  no implicit conversion of nil into Hash

Potential root cause:
* config.rb merges @site.config['responsive_image'] without checking if it exists

Expected behaviour:
* Warn about missing site.config, but continue to run with defaults

Workaround:
* add "responsive_image" section to _config.yml

**Comment by wildlyinaccurate** [comment]
Thanks, this is a great suggestion! I've just made two changes:

 - b76e2d33658c76f231a599cd36e276f2da2d16d4 - Clarify in the README that a `responsive_image` config is required
 - c559bcced3f3bcd36dc1b660b9e3b243099b7610 - Don't raise an exception when the config is missing
