### ISSUE TITLE
Liquid filters (specifically `absolute_url`) break build if used in the responsive image template

### ISSUE THREAD

**Issue by jerturowetz** [wildlyinaccurate/jekyll-responsive-image#78]
If I try to use liquid filters in the responsive image template file I get the following error:

```Liquid Exception: undefined method `config' for nil:NilClass in /_layouts/default.html```

## Example template file

The following are the contents of my template file. When I remove the `| absolute_url` filter everything works fine.

```
{% assign largest = resized | sort: 'width' | last %}
{% capture srcset %}
{% for i in resized %}
    /{{ i.path }} {{ i.width }}w,
{% endfor %}
    /{{ path }} {{ original.width }}w
{% endcapture %}

<img src="{{ path | absolute_url }}" alt="{{ alt }}" class="{{ class }}" srcset="{{ srcset | strip_newlines }}" sizes="{{ sizes }}" />
```

## System information

- jekyll-responsive-image 1.5.2
- jekyll 3.8.4
- ruby 2.4.4p296 (2018-03-28 revision 63013) [x64-mingw32]
- Windows 10
- Using MinGW64

## Expectations

**Expected behaviour:** Liquid filters accessible
**Actual behaviour:** No worky

**Comment by wildlyinaccurate** [comment]
Hmm, this might be a tricky one. I don't have time to look into a proper fix right now, but I think you should be able to get around it by doing something like this instead:

```
{% assign url = path | absolute_url %}
<img src="{{ url }}">
```

**Comment by jerturowetz** [comment]
I did not yet try that one, lemme give it a go and advise.

**Comment by iangreenleaf** [comment]
The suggested workaround did not work for me, but I was able to get a (fragile) solution with:

```
<img src="{{ site.url }}/{{ path }}" />
```

**Comment by iangreenleaf** [comment]
Would still love to see this fixed.
