### ISSUE TITLE
Passing a variable into the plugin?

### ISSUE THREAD

**Issue by Jules2010** [wildlyinaccurate/jekyll-responsive-image#81]
I'm trying to pass a variable into the plugin..

This is what I have currently...

```
{% for i in site.data.stt_screenshots %}
    <a href="/static/stt_screenshots/{{ i.image }}" class="thickbox">

        <div class="project-img bordered" 
style="background-image: url('/static/stt_screenshots/{{ i.image }}');"></div>

    </a>
{% endfor %}
```
I need to pass the `i.image` variable into the this plugin...
```
{% responsive_image 
path: static/stt_screenshots/variable?? 
title: "Lorem ipsum..." 
width: 300 %}
```

I've wrapped the code above, so it will fit.

I've tried various syntax, maybe there is a means to work around this?

Thanks in advance.

EDIT: Further attempts
```
{% capture thispath %}{{ site.baseurl }}/static/stt_screenshots/{{ x.image }}
{% endcapture %}
<img src="{{ thispath }}"></img>

{% responsive_image path: thispath alt: "Lorem ipsum..." 
template: _includes/responsive-screenshots.html %}

```

It seems like the plugin doesn't like the variable, not the template which uses the variable...
```
  Liquid Exception: Invalid image path specified: thispath in 
/_layouts/stt_screenshots.html
bundler: failed to load command: jekyll (/usr/local/bin/jekyll)
```

**Comment by Jules2010** [comment]
@wildlyinaccurate any thoughts?

**Comment by wildlyinaccurate** [comment]
Did you try using `responsive_image_block`? There are [some examples in the README](https://github.com/wildlyinaccurate/jekyll-responsive-image/blob/master/README.md#liquid-variables-as-attributes).

**Comment by Jules2010** [comment]
Thanks so much !
