### ISSUE TITLE
Doesn't work with jekyll-postfiles

### ISSUE THREAD

**Issue by wiseman** [wildlyinaccurate/jekyll-responsive-image#83]
This plugin currently doesn't work with the [jekyll-postfiles](https://github.com/nhoizey/jekyll-postfiles) plugin. I wish it did!  Any thoughts on whether that could ever happen?

**Comment by wildlyinaccurate** [comment]
I haven't used jekyll-postfiles so I might be missing something, but I think the two plugins should work fine together. It may just be a case of ensuring that jekyll-responsive-image runs before jekyll-postfiles.

If you have the time and the inclination, you could create a repo with a very basic Jekyll site with these two plugins installed. I'd be happy to take a look at it and see if there are any changes I can make to this plugin to make them play nicely together.
