### ISSUE TITLE
background-images ?

### ISSUE THREAD

**Issue by grauschnabel** [wildlyinaccurate/jekyll-responsive-image#84]
Hi there,

can this be used for backgroud images (the css background-image attribute) too?

If so, could you provide an example template for that?

Martin

**Comment by wildlyinaccurate** [comment]
You can `extra_images` config to force the plugin to resize images that are not used in posts (e.g. images that are used only in stylesheets). This plugin can't be used to generate the stylesheet though, so you will have to write the CSS yourself.

**Comment by grauschnabel** [comment]
Maybe I could set a `style` tag with the background-image in the template?

**Comment by wildlyinaccurate** [comment]
Yeah I think that would work. Just out of curiosity: are you doing responsive background-image?

**Comment by grauschnabel** [comment]
I'm not sure how this works, but I would like to try...
