### ISSUE TITLE
Liquid Exception: undefined method `start_with?' for nil:NilClass

### ISSUE THREAD

**Issue by JarekParal** [wildlyinaccurate/jekyll-responsive-image#88]
I have issue with `jekyll-responsive-image` after update from `jekyll-minimagic`.

I tried to update [our pages](https://github.com/RoboticsBrno/roboruka.robotickytabor.cz/issues/44) to Jekyll 4.x and replace plugin `jekyll-minimagic` with `jekyll-responsive-image` but I stuck on this [exception](https://travis-ci.org/RoboticsBrno/roboruka.robotickytabor.cz/jobs/654416428#L330):
```
 Liquid Exception: undefined method `start_with?' for nil:NilClass in /home/travis/build/RoboticsBrno/roboruka.robotickytabor.cz/_guides/002 - Obecné rady.md
/home/travis/.rvm/gems/ruby-2.5.3/gems/jekyll-4.0.0/lib/jekyll.rb:175:in `sanitized_path': undefined method `start_with?' for nil:NilClass (NoMethodError)
	from /home/travis/.rvm/gems/ruby-2.5.3/gems/jekyll-4.0.0/lib/jekyll/site.rb:380:in `block in in_source_dir'
	from /home/travis/.rvm/gems/ruby-2.5.3/gems/jekyll-4.0.0/lib/jekyll/site.rb:379:in `each'
	from /home/travis/.rvm/gems/ruby-2.5.3/gems/jekyll-4.0.0/lib/jekyll/site.rb:379:in `reduce'
	from /home/travis/.rvm/gems/ruby-2.5.3/gems/jekyll-4.0.0/lib/jekyll/site.rb:379:in `in_source_dir'
	from /home/travis/.rvm/gems/ruby-2.5.3/gems/jekyll-responsive-image-1.5.4/lib/jekyll-responsive-image/renderer.rb:24:in `render_responsive_image'
	from /home/travis/.rvm/gems/ruby-2.5.3/gems/jekyll-responsive-image-1.5.4/lib/jekyll-responsive-image/block.rb:8:in `render'
	from /home/travis/.rvm/gems/ruby-2.5.3/gems/liquid-4.0.3/lib/liquid/block_body.rb:103:in `render_node_to_output'
	from /home/travis/.rvm/gems/ruby-2.5.3/gems/liquid-4.0.3/lib/liquid/block_body.rb:82:in `render'
	...
```

Could you please help with fixing this issue?

**Comment by wildlyinaccurate** [comment]
Jekyll is throwing this exception, not the plugin. Judging by the line numbers, it seems like this would only happen if the "template" config was nil. But I can see your _config.yml has a valid "template" config, so I'm not sure.

I would start by debugging `in_source_dir` in jekyll/site.rb. See what values are being passed in, and if anything obvious stands out.
