### ISSUE TITLE
Conversion without resizing

### ISSUE THREAD

**Issue by CodeSandwich** [wildlyinaccurate/jekyll-responsive-image#91]
### Situation
I have a set of big source JPG images compressed with quality ~95. Their resolution is useful for really big screens, but they are too heavy. It would make sense to have them recompressed with quality 70 and use as a `src` and the biggest `srcset`.

### Solution
Allow `sizes[ { width: 0 }, ...]`, which would be a placeholder for processing with no resizing.

What do you think about this idea?

**Comment by wildlyinaccurate** [comment]
For similar reasons as #92, I don't think this feature belongs in this plugin. I suggest you keep your source images as high resolution and high quality, but add a resize width for large screens.
