### ISSUE TITLE
Format change

### ISSUE THREAD

**Issue by CodeSandwich** [wildlyinaccurate/jekyll-responsive-image#92]
### Situation
I have a set of big source PNG images. It would make sense to have them recompressed as JPG.

### Solution
Add to configuration `default_format: jpg|png|webm` and `sizes: [ { ... format: jpg|png|webm }]`, which would allow controlling the output format. It would play along greatly with https://github.com/wildlyinaccurate/jekyll-responsive-image/issues/91 to provide a non-resized, but recompressed source image.

What do you think about this idea?

**Comment by wildlyinaccurate** [comment]
I appreciate the suggestion, but I'm trying to keep the scope of this plugin as narrow as possible. I suggest you save your source images in the format that you want them to be delivered as.

**Comment by Lominean** [comment]
It would be a nice workflow to be able to check in uncompressed fullres images and have a Jekyll plugin convert _and_ resize during build.
