### ISSUE TITLE
output_path_format does not work when save_to_source is false

### ISSUE THREAD

**Issue by trombik** [wildlyinaccurate/jekyll-responsive-image#94]
as an author, I would like to keep original images in git repository, but not resized images, so that I only manage originals, and images are resized before deployment and served.

`output_path_format` is set to retain the original directory structure. `save_to_source` is set to false. my expectation is that:

1. `assets/img/resized` should not exist
1. `_site/assets/img/resized` should exist, and resized images should be there

but the resized files are not in `_site/assets/img/resized`. `_site/assets/img/resized` does not even exist.

```console
> ls _site/assets/img/resized
ls: _site/assets/img/resized: No such file or directory
```

using the full path in the log produces the same result.

```console
> ls /usr/home/trombik/github/trombik/jekyll-site-info.i.mkrsgh.org/_site/assets/img/resized/                      
ls: /usr/home/trombik/github/trombik/jekyll-site-info.i.mkrsgh.org/_site/assets/img/resized/: No such file or directory
```

at least, the plugin does not create resized file in the source. `save_to_source: false` does work.

```console
> ls assets/img/resized
ls: assets/img/resized: No such file or directory
```

the same symptom was [reported in the past](https://github.com/wildlyinaccurate/jekyll-responsive-image/issues/1#issuecomment-155824498). 

here is the log.

```console
> bundle exec jekyll browsersync --drafts 
Configuration file: /usr/home/trombik/github/trombik/jekyll-site-info.i.mkrsgh.org/_config.yml
            Source: /usr/home/trombik/github/trombik/jekyll-site-info.i.mkrsgh.org
       Destination: /usr/home/trombik/github/trombik/jekyll-site-info.i.mkrsgh.org/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
        Pagination: Pagination is enabled, but I couldn't find an index.html page to use as the pagination template. Skipping pagination.
       Jekyll Feed: Generating feed for posts
       Jekyll Feed: Generating feed for posts
Creating output directory /usr/home/trombik/github/trombik/jekyll-site-info.i.mkrsgh.org/_site/assets/img/resized 
Generating /usr/home/trombik/github/trombik/jekyll-site-info.i.mkrsgh.org/_site/assets/img/resized/Quiet-Alley-480x853.jpg 
Generating /usr/home/trombik/github/trombik/jekyll-site-info.i.mkrsgh.org/_site/assets/img/resized/Busy-Alley-480x853.jpg 
                    done in 1.526 seconds.
  Please add the following to your Gemfile to avoid polling for changes:
    require 'rbconfig'
    if RbConfig::CONFIG['target_os'] =~ /(?i-mx:bsd|dragonfly)/
      gem 'rb-kqueue', '>= 0.2'
    end
 Auto-regeneration: enabled for '/usr/home/trombik/github/trombik/jekyll-site-info.i.mkrsgh.org'
[Browsersync] Access URLs: 
 ---------------------------------- 
       Local: http://localhost:4000 
    External: http://127.0.0.1:4000 
 ---------------------------------- 
          UI: http://localhost:3001 
 UI External: http://localhost:3001 
 ---------------------------------- 
[Browsersync] Serving files from: /usr/home/trombik/github/trombik/jekyll-site-info.i.mkrsgh.org/_site 
[Browsersync] Watching files... 
```

_config.yml

```yam
responsive_image:
  template: _includes/local/srcset-resized-fallback.html
  default_quality: 90
  sizes:
    - width: 480
    - width: 800
    - width: 1500
  output_path_format: assets/%{dirname}/resized/%{filename}-%{width}x%{height}.%{extension}
  save_to_source: false
```

versions in Gemfile.lock

```
    jekyll-responsive-image (1.5.5)
    jekyll (4.1.0)
```

```html
{% assign largest = resized | sort: 'width' | last %}
{% capture srcset %}
{% for i in resized %}
    /{{ i.path }} {{ i.width }}w,
{% endfor %}
{% endcapture %}
<figure class="{{ class }}">
  <img src="/{{ largest.path }}"
       alt="{{ alt }}"
       srcset="{{ srcset | strip_newlines }} /{{ path }} {{ original.width }}w"
       >
  {% if caption %}
    <figcaption>
      {{ caption }}
    </figcaption>
  {% endif %}
</figure>
```

**Comment by trombik** [comment]
the workaround is:

- set `save_to_source` to true
- add the directory for the resized in the source to `.gitignore`

**Comment by wildlyinaccurate** [comment]
Is the log you posted from the first run or a subsequent run? These logs indicate the files are being created:

```
Creating output directory /usr/home/trombik/github/trombik/jekyll-site-info.i.mkrsgh.org/_site/assets/img/resized 
Generating /usr/home/trombik/github/trombik/jekyll-site-info.i.mkrsgh.org/_site/assets/img/resized/Quiet-Alley-480x853.jpg 
Generating /usr/home/trombik/github/trombik/jekyll-site-info.i.mkrsgh.org/_site/assets/img/resized/Busy-Alley-480x853.jpg 
```

**Comment by trombik** [comment]
the first run. I know the log entries says the plugin created files and directories. but the after the build, `ls` says the files disappeared. I am guessing that it has something to do with the sequence jekyll executes plugins. `_site` directory is not supposed to be populated by plugins, I guess. your test uses version 4.0.0, but mine is 4.1.0.

**Comment by wildlyinaccurate** [comment]
My first guess is that the `browsersync` (and maybe the `serve`) command are performing some cleanup that is removing the files. Could you try with `jekyll build`? My second guess is another plugin is messing with the files, although that seems unlikely.

To be honest I never use `save_to_source: false`, so it's possible that Jekyll's behaviour around saving files directly to the `_site/` directory has changed. For all of my sites I use your second option (add the resized source directory to `.gitignore`).
