### ISSUE TITLE
Can't seem to get working with any of the templates, perhaps because it's in a column?

### ISSUE THREAD

**Issue by improvethings** [wildlyinaccurate/jekyll-responsive-image#95]
jekyll (= 3.8.7)
jekyll-responsive-image (1.5.5)
      jekyll (>= 2.0, < 5.0)
      rmagick (>= 2.0, < 5.0)

sourcecode_filename.md:

<div class="row">
    <div class="col-md-6">
<iframe src="https://docs.google.com/forms/d/blah/viewform?embedded=true" width="340" height="300" frameborder="0" marginheight="0" marginwidth="0">Loading…</iframe>
    </div>
    <div class="col-md-6">
     
THIS IS WHERE THE IMAGE GOES

    </div>
</div>

$ file assets/images/man-in-blue-suit.jpg 
assets/images/man-in-blue-suit.jpg: JPEG image data, JFIF standard 1.01, resolution (DPI), density 72x72, segment length 16, Exif Standard: [TIFF image data, little-endian, direntries=16, height=3376, bps=206, PhotometricIntepretation=RGB, manufacturer=FUJIFILM, model=X-T20, orientation=upper-left, width=6000], baseline, precision 8, 574x337, components 3
$ ls -l assets/images/man-in-blue-suit.jpg 
-rw-r--r-- 1 me me 210516 Jul 15 11:53 assets/images/man-in-blue-suit.jpg

I tried each of the four templates. For each template I'll explain what I see in brackets, and the section from view source: 

imager-js.html: (image appears as missing)

<div class="responsive-image">
    <img class="responsive-image__placeholder" src="/" />
    <div class="responsive-image__delayed" data-src="/assets/resized/{width}/man-in-blue-suit.jpg"></div>
</div>

<script>
new Imager('.responsive-image__delayed', {
    availableWidths: [],
    onImagesReplaced: function() {
        $('.responsive-image__placeholder').hide()
    }
})
</script>

picture.html:  (image always stays original size even on mobile)

  <picture>
    
    <img src="/assets/images/man-in-blue-suit.jpg" />
</picture>

srcset-resized-fallback.html: (pic is way larger than original, goes off screen on desktop)

<img src="/" alt="Man in blue suit" srcset=" /assets/images/man-in-blue-suit.jpg 574w" />

srcset.html: (pic is way larger than original, goes off screen on desktop) 

<img src="/assets/images/man-in-blue-suit.jpg" alt="Man in blue suit" srcset=" /assets/images/man-in-blue-suit.jpg 574w" />

**Comment by wildlyinaccurate** [comment]
I can't offer you any support for how you implement responsive images, sorry. The templates provided with the plugin are examples that you will need to adapt to work with your site's markup and styling.

**Comment by wildlyinaccurate** [comment]
Ah, I just realised there's a bunch of markup not showing in your comment. If you wrap your code in triple-backticks like this, it will show up correctly:

```
    ```
    <div>
        blah
    </div>
    ````
```

It looks like the original picture is 574px wide, and there is no resizing occurring (you can tell because only the `574w` source is being output in the srcset template. Can you paste the output of your config.yml?
