### ISSUE TITLE
Using jekyll-responsive-images with Markdown

### ISSUE THREAD

**Issue by raulcraveiro** [wildlyinaccurate/jekyll-responsive-image#97]
Is there a way to use the jekyll-responsive-images plugin using the image markdown tag?

**Comment by wildlyinaccurate** [comment]
This plugin only provides the tags. You could experiment with building [a converter](https://jekyllrb.com/docs/plugins/converters/) that converted Markdown image tags to `{% responsive_image %}` tags?
